[versions]
agp = "8.1.1"
androidCompileSdk = "34"
androidMinSdk = "23"
androidTargetSdk = "34"
androidTestCore = "1.5.0"
androidTestRunner = "1.5.2"

composeBom = "2023.08.00"
composeCompiler = "1.5.1"
constraintlayout = "2.1.4"
coroutines = "1.7.1"

datastore = "1.0.0"

fragment = "1.6.1"

hilt = "2.47"

junit = "5.10.0"

koin = "3.4.3"
kotlin = "1.9.0"
ksp = "1.9.0-1.0.13"

lifecycle = "2.6.1"

mockk = "1.13.7"

navigation = "2.7.1"

robolectric = "4.10.3"
room = "2.5.2"

savedstate = "1.2.1"

[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit" }

koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

test-core = { module = "androidx.test:core", version.ref = "androidTestCore" }
test-runner = { module = "androidx.test:runner", version.ref = "androidTestRunner" }
